version: '3'

services:
  redis_cache:
    image: redis
    restart: always
    container_name: webstore_redis_cache
    ports:
      - "6379:6379"

  postgres_db:
    image: postgres
    restart: always
    container_name: webstore_postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=super_secret
      - POSTGRES_DB=webstore
    ports:
      - "5433:5432"

  celery_worker:
    build: .
    volumes:
      - .:/home/project
    container_name: celery_worker
    command: celery -A config worker -l info
    restart: always
    depends_on:
      - postgres_db
      - redis_cache

  webstore:
    build: .
    container_name: django_webstore
    volumes:
      - .:/home/project
    command: ./manage.py runserver 0.0.0.0:8000 --settings=config.settings.docker
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis_cache
      - celery_worker