version: '3'

services:
  redis_cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=super_secret
      - POSTGRES_DB=webstore
    ports:
      - "5433:5432"
  webstore:
    build: .
    volumes:
      - .:/home/project
    command: ./manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis_cache